# Generated by Django 5.1.6 on 2025-02-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pychai', '0005_alter_chaivariety_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaivariety',
            name='user',
        ),
    ]
